# cache
cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
  paths:
  - .env
  - vendor/

# Before Script
before_script:
  - echo 'Building start...'

verify:
  script:
    - ant verify
