# cache
cache:
  paths:
  - .env
  - vendor/

# Before Script
before_script:
  - composer self-update
  - composer install --prefer-dist > /dev/null
  - php artisan migrate:reset
  - php artisan migrate


# PHP 7.0
php:7.0:
  script:
    - ant
