<?php

return [
    'store' => [
        'BCAMAZONUS' => [
            'merchantId' => 'A31GWB3ZYX0LWJ',
            'marketplaceId' => 'ATVPDKIKX0DER',
            'keyId' => 'AKIAJV4DKBKNNPD4EXEA', // Access Key ID.
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.com/',
            'platform' => 'US',
        ],
        'BCAMAZONCA' => [
            'merchantId' => 'A31GWB3ZYX0LWJ',
            'marketplaceId' => 'A2EUQ1WTGCTBG2',
            'keyId' => 'AKIAJV4DKBKNNPD4EXEA',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.ca/',
            'platform' =>'CA',
        ],
        'BCAMAZONMX' => [
            'merchantId' => 'A31GWB3ZYX0LWJ',
            'marketplaceId' => 'A1AM78C64UM0Y8',
            'keyId' => 'AKIAJV4DKBKNNPD4EXEA',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.com.mx/',
            'platform' =>'MX',
        ],
        'BCAMAZONGB' => [
            'merchantId' => 'A3C4BSI6HUJD6J',
            'marketplaceId' => 'A1F83G8C2ARO7P',
            'keyId' => 'AKIAIYWCWNJO3QP2BNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.co.uk/',
            'platform' =>'GB',
        ],
        'BCAMAZONDE' => [
            'merchantId' => 'A3C4BSI6HUJD6J',
            'marketplaceId' => 'A1PA6795UKMFR9',
            'keyId' => 'AKIAIYWCWNJO3QP2BNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.de/',
            'platform' =>'DE',
        ],
        'BCAMAZONES' => [
            'merchantId' => 'A3C4BSI6HUJD6J',
            'marketplaceId' => 'A1RKKUPIHCS9HS',
            'keyId' => 'AKIAIYWCWNJO3QP2BNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.es/',
            'platform' =>'ES',
        ],
        'BCAMAZONFR' => [
            'merchantId' => 'A3C4BSI6HUJD6J',
            'marketplaceId' => 'A13V1IB3VIYZZH',
            'keyId' => 'AKIAIYWCWNJO3QP2BNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.fr/',
            'platform' =>'FR',
        ],
        'BCAMAZONIT' => [
            'merchantId' => 'A3C4BSI6HUJD6J',
            'marketplaceId' => 'APJ6JRA9NG5V4',
            'keyId' => 'AKIAIYWCWNJO3QP2BNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.it/',
            'platform' =>'IT',
        ],
        'BCAMAZONJP' => [
            'merchantId' => 'A31MKVVQWZLA3D',
            'marketplaceId' => 'A1VC38T7YXB528',
            'keyId' => 'AKIAJ7FBNDUIX7XLPNZQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.jp/',
            'platform' =>'JP',
        ],

        'PXAMAZONGB' => [
            'merchantId' => 'AK4II4CA9MIL3',
            'marketplaceId' => 'A1F83G8C2ARO7P',
            'keyId' => 'AKIAJ5HB6U2UVGWXODAQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.co.uk/',
            'platform' =>'GB',
        ],
        'PXAMAZONDE' => [
            'merchantId' => 'AK4II4CA9MIL3',
            'marketplaceId' => 'A1PA6795UKMFR9',
            'keyId' => 'AKIAJ5HB6U2UVGWXODAQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.de/',
            'platform' =>'DE',
        ],
        'PXAMAZONES' => [
            'merchantId' => 'AK4II4CA9MIL3',
            'marketplaceId' => 'A1RKKUPIHCS9HS',
            'keyId' => 'AKIAJ5HB6U2UVGWXODAQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.es/',
            'platform' =>'ES',
        ],
        'PXAMAZONFR' => [
            'merchantId' => 'AK4II4CA9MIL3',
            'marketplaceId' => 'A13V1IB3VIYZZH',
            'keyId' => 'AKIAJ5HB6U2UVGWXODAQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.fr/',
            'platform' =>'FR',
        ],
        'PXAMAZONIT' => [
            'merchantId' => 'AK4II4CA9MIL3',
            'marketplaceId' => 'APJ6JRA9NG5V4',
            'keyId' => 'AKIAJ5HB6U2UVGWXODAQ',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.it/',
            'platform' =>'IT',
        ],

        'CVAMAZONUS' => [
            'merchantId' => 'A2FG3KS48AERP3',
            'marketplaceId' => 'ATVPDKIKX0DER',
            'keyId' => 'AKIAIE6UJ4WHVNQHZ37A', // Access Key ID.
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.com/',
            'platform' => 'US',
        ],
        'CVAMAZONCA' => [
            'merchantId' => 'A2FG3KS48AERP3',
            'marketplaceId' => 'A2EUQ1WTGCTBG2',
            'keyId' => 'AKIAIE6UJ4WHVNQHZ37A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.ca/',
            'platform' =>'CA',
        ],
        'CVAMAZONMX' => [
            'merchantId' => 'A2FG3KS48AERP3',
            'marketplaceId' => 'A1AM78C64UM0Y8',
            'keyId' => 'AKIAIE6UJ4WHVNQHZ37A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.com.mx/',
            'platform' =>'MX',
        ],
        'CVAMAZONGB' => [
            'merchantId' => 'A2FP4K69BWZNT0',
            'marketplaceId' => 'A1F83G8C2ARO7P',
            'keyId' => 'AKIAIDQTDZZCXFWI4O2A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.co.uk/',
            'platform' =>'GB',
        ],
        'CVAMAZONDE' => [
            'merchantId' => 'A2FP4K69BWZNT0',
            'marketplaceId' => 'A1PA6795UKMFR9',
            'keyId' => 'AKIAIDQTDZZCXFWI4O2A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.de/',
            'platform' =>'DE',
        ],
        'CVAMAZONES' => [
            'merchantId' => 'A2FP4K69BWZNT0',
            'marketplaceId' => 'A1RKKUPIHCS9HS',
            'keyId' => 'AKIAIDQTDZZCXFWI4O2A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.es/',
            'platform' =>'ES',
        ],
        'CVAMAZONFR' => [
            'merchantId' => 'A2FP4K69BWZNT0',
            'marketplaceId' => 'A13V1IB3VIYZZH',
            'keyId' => 'AKIAIDQTDZZCXFWI4O2A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.fr/',
            'platform' =>'FR',
        ],
        'CVAMAZONIT' => [
            'merchantId' => 'A2FP4K69BWZNT0',
            'marketplaceId' => 'APJ6JRA9NG5V4',
            'keyId' => 'AKIAIDQTDZZCXFWI4O2A',
            'secretKey' => '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',
            'amazonServiceUrl' => 'https://mws.amazonservices.it/',
            'platform' =>'IT',
        ],

        // '3DAMAZONUS' => [
        //     'merchantId' => 'A596P66U645JG',
        //     'marketplaceId' => 'ATVPDKIKX0DER',
        //     'keyId' => 'AKIAJKXSW24CHZEO64WQ',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.com/',
        //     'platform' =>'US',
        // ],
        // '3DAMAZONCA' => [
        //     'merchantId' => 'A596P66U645JG',
        //     'marketplaceId' => 'A2EUQ1WTGCTBG2',
        //     'keyId' => 'AKIAJKXSW24CHZEO64WQ',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.ca/',
        //     'platform' =>'CA',
        // ],
        // '3DAMAZONMX' => [
        //     'merchantId' => 'A596P66U645JG',
        //     'marketplaceId' => 'A1AM78C64UM0Y8',
        //     'keyId' => 'AKIAJKXSW24CHZEO64WQ',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.com.mx/',
        //     'platform' =>'MX',
        // ],
        // '3DAMAZONGB' => [
        //     'merchantId' => 'A2LTPCO6A3S9S4',
        //     'marketplaceId' => 'A1F83G8C2ARO7P',
        //     'keyId' => 'AKIAJXJU4CCFR7SQWZUA',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.co.uk/',
        //     'platform' =>'GB',
        // ],
        // '3DAMAZONDE' => [
        //     'merchantId' => 'A2LTPCO6A3S9S4',
        //     'marketplaceId' => 'A1PA6795UKMFR9',
        //     'keyId' => 'AKIAJXJU4CCFR7SQWZUA',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.de/',
        //     'platform' =>'DE',
        // ],
        // '3DAMAZONES' => [
        //     'merchantId' => 'A2LTPCO6A3S9S4',
        //     'marketplaceId' => 'A1RKKUPIHCS9HS',
        //     'keyId' => 'AKIAJXJU4CCFR7SQWZUA',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.es/',
        //     'platform' =>'ES',
        // ],
        // '3DAMAZONFR' => [
        //     'merchantId' => 'A2LTPCO6A3S9S4',
        //     'marketplaceId' => 'A13V1IB3VIYZZH',
        //     'keyId' => 'AKIAJXJU4CCFR7SQWZUA',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.fr/',
        //     'platform' =>'FR',
        // ],
        // '3DAMAZONIT' => [
        //     'merchantId' => 'A2LTPCO6A3S9S4',
        //     'marketplaceId' => 'APJ6JRA9NG5V4',
        //     'keyId' => 'AKIAJXJU4CCFR7SQWZUA',
        //     'secretKey' => '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',
        //     'amazonServiceUrl' => 'https://mws.amazonservices.it/',
        //     'platform' =>'IT',
        // ],
    ],

    // Default service URL
    'AMAZON_SERVICE_URL' => 'https://mws.amazonservices.com/',

    'muteLog' => true
];
