<?php

return [
    'store' => [
        'BCLAZADAMY' => [
            'name'=>'Brands Connect Lazada',
            'userId' => 'lazadamy@brandsconnect.net', 
            'apiToken' => '8742efca4d071f92cf07e2c4ff53c4cd0d0725b7',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'BCLAZADASG' => [
            'name'=>'Brands Connect Lazada',
            'userId' => 'lazadamy@brandsconnect.net', 
            'apiToken' => '6ff07b03f6176e63c673e3d6e45e6122e7c96800',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'BCLAZADATH' => [
            'name'=>'Brands Connect Lazada',
            'userId' => 'lazadamy@brandsconnect.net', 
            'apiToken' => '5186db6640a60a4bf7b18bdae3e304da112c45e8',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'BCLAZADAPH' => [
            'name'=>'Brands Connect Lazada',
            'userId' => 'lazadamy@brandsconnect.net', 
            'apiToken' => 'e3ba45edd9b21f2ea0f7b11a0399fb8c88ae570e',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'BCLAZADAID' => [
            'name'=>'Brands Connect Lazada',
            'userId' => 'lazadamy@brandsconnect.net', 
            'apiToken' => '9d1fe86c46aa853a57bcfc84d2df2f19b335f5db',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],
        'CSLAZADAMY' => [
            'name'=>'Cambridge Soundworks Lazada',
            'userId' => 'cambridgesoundworks@aheaddigital.net', 
            'apiToken' => 'b0e69bc90bfe709b078066864532c7f8f39eb754',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'CSLAZADASG' => [
            'name'=>'Cambridge Soundworks Lazada',
            'userId' => 'cambridgesoundworks@aheaddigital.net', 
            'apiToken' => '2426c81661c652cde833fc580735eb27c1553e20',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'CSLAZADATH' => [
            'name'=>'Cambridge Soundworks Lazada',
            'userId' => 'cambridgesoundworks@aheaddigital.net', 
            'apiToken' => '533bdb068f20d310aca7b9cea6df3e8ff98f6501',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'CSLAZADAPH' => [
            'name'=>'Cambridge Soundworks Lazada',
            'userId' => 'cambridgesoundworks@aheaddigital.net', 
            'apiToken' => '81ccf5c473cc53c990d3fbdd0c0facdb8f1c754f',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'CSLAZADAID' => [
            'name'=>'Cambridge Soundworks Lazada',
            'userId' => 'cambridgesoundworks@aheaddigital.net', 
            'apiToken' => 'a5db4b917dda27071c18bd96a9c9c30b14a042e5',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],

        'MDLAZADAMY' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'mattelmy@eservicesgroup.com', 
            'apiToken' => '5d89e6945a21e101e57884095318a2d88207ee54',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'MDLAZADASG' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'mattelsg@eservicesgroup.com', 
            'apiToken' => '',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'MDLAZADATH' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'mattelth@eservicesgroup.com', 
            'apiToken' => '9924355a94c3681bbd3dfa3a695b5c77f2dca040',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'MDLAZADAPH' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'mattelph@eservicesgroup.com', 
            'apiToken' => 'bce3f59555c439d60f6b0ecdaf32c2f737e76142',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
       'MDLAZADAID' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'Mattelid@eservicesgroup.com', 
            'apiToken' => 'adb169090e17dc46bb09e99bff7f575886dd76db',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],
        'MDLAZADAVN' => [
            'name'=>'Mattel Distributor Lazada',
            'userId' => 'mattelvn@eservicesgroup.com', 
            'apiToken' => '6560c4c98f0281ca707fd1ba43ee94a1b8d309ad',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.vn/',
            'currency'=>'VND',
        ],
        'MLLAZADAMY' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => '820f616e3e10a4f9982973c9d113027525519d2d',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'MLLAZADASG' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => '646a5c11c0f975cd4ff0b26618ea7387489cb48c',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'MLLAZADATH' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => '942c473bfec88dfa493837d74c4610651d14d5bc',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'MLLAZADAPH' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => 'c6449f2fc5cea3a15ff4b65641f801077ba9f661',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'MLLAZADAID' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => 'e6b25997f5603cb47524fc73b1462f14bc6bfbbe',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],
        'MLLAZADAVN' => [
            'name'=>'Mattel Lazada',
            'userId' => 'mattel@apresslink.com', 
            'apiToken' => '9915f134ae8fe3b445129c81a26f120c668a6a73',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.vn/',
            'currency'=>'VND',
        ],
        
        'CFLAZADAMY' => [
            'name'=>'China Finest Lazada',
            'userId' => 'lazada@eservicesgroup.com', 
            'apiToken' => '575f613e83fee7f0a2b3098110b177109a20fa47',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'CFLAZADASG' => [
            'name'=>'China Finest Lazada',
            'userId' => 'lazada@eservicesgroup.com', 
            'apiToken' => '1bf34d47695451e80b9b05fcb22d86e3281ba84f',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'CFLAZADATH' => [
            'name'=>'China Finest Lazada',
            'userId' => 'lazada@eservicesgroup.com', 
            'apiToken' => '0f42c6115fe80506ce52d7c452fe5991ede50e1f',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'CFLAZADAPH' => [
            'name'=>'China Finest Lazada',
            'userId' => 'lazada@eservicesgroup.com', 
            'apiToken' => '73fb06dc02628a9797dc2759945e372a745f0a4d',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'CFLAZADAID' => [
            'name'=>'China Finest Lazada',
            'userId' => 'lazada@eservicesgroup.com', 
            'apiToken' => '9cfc107ba37aef42b1f6911489f8b49f6e077f52',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],

        '3DLAZADAMY' => [
            'name'=>'3Doodler Lazada',
            'userId' => '3doodler@buholoco.com', 
            'apiToken' => '09fafcc3bf9875c9775e87a09d6b85aecb3a8414',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        '3DLAZADASG' => [
            'name'=>'3Doodler Lazada',
            'userId' => '3doodler@buholoco.com', 
            'apiToken' => '40a59e81aea09626d2aee6959e91ca5e089936aa',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        '3DLAZADATH' => [
            'name'=>'3Doodler Lazada',
            'userId' => '3doodler@buholoco.com', 
            'apiToken' => 'dcff9675060bb50d5aaa5057fb9c57e0de8e5665',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        '3DLAZADAPH' => [
            'name'=>'3Doodler Lazada',
            'userId' => '3doodler@buholoco.com', 
            'apiToken' => '2bb586ed7cd9f0e8b1d264f43bdafd19e41cdcfd',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        '3DLAZADAID' => [
            'name'=>'3Doodler Lazada',
            'userId' => '3doodler@buholoco.com', 
            'apiToken' => 'c20fb2bf08a184acb970082375e8b7fb8fac167b',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],

        'BMLAZADAMY' => [
            'name'=>'Blue Microphones Lazada',
            'userId' => 'bluemic@chatandvision.com', 
            'apiToken' => '045edaea84249942a614cf7d20c2747e3566b36d',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'BMLAZADASG' => [
            'name'=>'Blue Microphones Lazada',
            'userId' => 'bluemic@chatandvision.com', 
            'apiToken' => '135e2b28fb87190348dd7222d2ed76bd8797f86b',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'BMLAZADATH' => [
            'name'=>'Blue Microphones Lazada',
            'userId' => 'bluemic@chatandvision.com', 
            'apiToken' => '333dbb7a2a8cb9649d4f7f561dd09e230327bade',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'BMLAZADAPH' => [
            'name'=>'Blue Microphones Lazada',
            'userId' => 'bluemic@chatandvision.com', 
            'apiToken' => '765181b74466d02e7b1eea0c5da4efeaad204bd7',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'BMLAZADAID' => [
            'name'=>'Blue Microphones Lazada',
            'userId' => 'bluemic@chatandvision.com', 
            'apiToken' => '8b765eb5720fcc970c80875b1058043001a6e836',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],

        'KALAZADAMY' => [
            'name'=>'KitchenAid International Lazada',
            'userId' => 'kitchenaid@nuovadigitale.com', 
            'apiToken' => '0745370dbea2c09eb5654b8051fe546ba5569fa6',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'KALAZADASG' => [
            'name'=>'KitchenAid International Lazada',
            'userId' => 'kitchenaid@nuovadigitale.com', 
            'apiToken' => '40d09351cf746d7742c36a13bd9492fd6a9c157b',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'KALAZADATH' => [
            'name'=>'KitchenAid International Lazada',
            'userId' => 'kitchenaid@nuovadigitale.com', 
            'apiToken' => 'ce136e48015ce0ac993f723aff9585002bdff9fc',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'KALAZADAPH' => [
            'name'=>'KitchenAid International Lazada',
            'userId' => 'kitchenaid@nuovadigitale.com', 
            'apiToken' => '680168a2623ff70b5d1c88f0130413fea0111791',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'KALAZADAID' => [
            'name'=>'KitchenAid International Lazada',
            'userId' => 'kitchenaid@nuovadigitale.com', 
            'apiToken' => 'b30599759a148a4f4df60b6c7a799a6ac26887d9',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],

        /*'VBLAZADAMY' => [
            'userId' => 'lazada@valuebasket.com', 
            'apiToken' => '03daeeb3ca4894a4b08ec27aa867a1c5b3eaa8ba',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.my/',
            'currency'=>'MYR',
        ],
        'VBLAZADASG' => [
            'userId' => 'lazada@valuebasket.com', 
            'apiToken' => '0d75f84b529e1bd60541a63a05ff2ce556bb400f',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.sg/',
            'currency'=>'SGD',
        ],
        'VBLAZADATH' => [
            'userId' => 'lazada@valuebasket.com', 
            'apiToken' => '7889f42693c762a66c8afc40c79038d66e71fbdc',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.th/',
            'currency'=>'THB',
        ],
        'VBLAZADAPH' => [
            'userId' => 'lazada@valuebasket.com', 
            'apiToken' => 'a06df56286d30189149e9a738edad80aee254358',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.com.ph/',
            'currency'=>'PHP',
        ],
        'VBLAZADAID' => [
            'userId' => 'lazada@valuebasket.com', 
            'apiToken' => '71f73342f5590237a093697034e6fc1e5ffa383e',
            'lazadaServiceUrl' => 'https://sellercenter-api.lazada.co.id/',
            'currency'=>'IDR',
        ],*/
    ],

    // Default service URL
    'LAZADA_SERVICE_URL' => 'https://sellercenter-api.lazada.com.my/',
    'muteLog' => true
];
